[project]
name = "fastapi-cicd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "fedora.laptop@tran-kt.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "uvicorn[standard]>=0.54.0",
]

[project.scripts]
fastapi-cicd = "fastapi_cicd:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
